In [80]:
import os
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
from sklearn import preprocessing

In [81]:
os.chdir("C:\\Users\\Archana\\Desktop\\datasets")

In [82]:
d=pd.read_csv("cancer.csv")
d.head(5)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

            ...             radius_worst  texture_worst  perimeter_worst  \
0           ...                    25.38          17.33           184.60   
1           ...                    24.99          23.41           158.80   
2           ...                    23.57          25.53           152.50   
3           ...                    14.91          26.50            98.87   
4           ...                    22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 32 columns]

In [83]:
d=d.drop(columns='id')

In [84]:
d.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean           ...             radius_worst  texture_worst  \
0         0.2419           ...                    25.38          17.33   
1         0.1812           ...                    24.99          23.41   
2         0.2069           ...                    23.57          25.53   
3         0.2597           ...                    14.91          26.50   
4         0.1809           ...                    22.54          16.67   

   perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
0           184.60      2019.0            0.1622             0.6656   
1           158.80      1956.0            0.1238             0.1866   
2           152.50      1709.0            0.1444             0.4245   
3            98.87       567.7            0.2098             0.8663   
4           152.20      1575.0            0.1374             0.2050   

   concavity_worst  concave points_worst  symmetry_worst  \
0           0.7119                0.2654          0.4601   
1           0.2416                0.1860          0.2750   
2           0.4504                0.2430          0.3613   
3           0.6869                0.2575          0.6638   
4           0.4000                0.1625          0.2364   

   fractal_dimension_worst  
0                  0.11890  
1                  0.08902  
2                  0.08758  
3                  0.17300  
4                  0.07678  

[5 rows x 31 columns]

In [85]:
d['diagnosis'].value_counts()

B    357
M    212
Name: diagnosis, dtype: int64

In [86]:
d['diagnosis'].replace(['M','B'],['Malignant','Benign'],inplace=True)

In [87]:
d.columns

Index(['diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [88]:
data=d.iloc[:,[1,3,4,5]]
data.head()

radius_mean  perimeter_mean  area_mean  smoothness_mean
0        17.99          122.80     1001.0          0.11840
1        20.57          132.90     1326.0          0.08474
2        19.69          130.00     1203.0          0.10960
3        11.42           77.58      386.1          0.14250
4        20.29          135.10     1297.0          0.10030

In [89]:
data.describe()

radius_mean  perimeter_mean    area_mean  smoothness_mean
count   569.000000      569.000000   569.000000       569.000000
mean     14.127292       91.969033   654.889104         0.096360
std       3.524049       24.298981   351.914129         0.014064
min       6.981000       43.790000   143.500000         0.052630
25%      11.700000       75.170000   420.300000         0.086370
50%      13.370000       86.240000   551.100000         0.095870
75%      15.780000      104.100000   782.700000         0.105300
max      28.110000      188.500000  2501.000000         0.163400

In [90]:
x=d.iloc[:,1:31]
x.head()

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   fractal_dimension_mean           ...             radius_worst  \
0                 0.07871           ...                    25.38   
1                 0.05667           ...                    24.99   
2                 0.05999           ...                    23.57   
3                 0.09744           ...                    14.91   
4                 0.05883           ...                    22.54   

   texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0          17.33           184.60      2019.0            0.1622   
1          23.41           158.80      1956.0            0.1238   
2          25.53           152.50      1709.0            0.1444   
3          26.50            98.87       567.7            0.2098   
4          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  
0                  0.11890  
1                  0.08902  
2                  0.08758  
3                  0.17300  
4                  0.07678  

[5 rows x 30 columns]

In [91]:
y=d.iloc[:,0]
y.head()

0    Malignant
1    Malignant
2    Malignant
3    Malignant
4    Malignant
Name: diagnosis, dtype: object

In [92]:
d['diagnosis'].replace(['Malignant','Benign'],[1,0],inplace=True)

In [93]:
d.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0          1        17.99         10.38          122.80     1001.0   
1          1        20.57         17.77          132.90     1326.0   
2          1        19.69         21.25          130.00     1203.0   
3          1        11.42         20.38           77.58      386.1   
4          1        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean           ...             radius_worst  texture_worst  \
0         0.2419           ...                    25.38          17.33   
1         0.1812           ...                    24.99          23.41   
2         0.2069           ...                    23.57          25.53   
3         0.2597           ...                    14.91          26.50   
4         0.1809           ...                    22.54          16.67   

   perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
0           184.60      2019.0            0.1622             0.6656   
1           158.80      1956.0            0.1238             0.1866   
2           152.50      1709.0            0.1444             0.4245   
3            98.87       567.7            0.2098             0.8663   
4           152.20      1575.0            0.1374             0.2050   

   concavity_worst  concave points_worst  symmetry_worst  \
0           0.7119                0.2654          0.4601   
1           0.2416                0.1860          0.2750   
2           0.4504                0.2430          0.3613   
3           0.6869                0.2575          0.6638   
4           0.4000                0.1625          0.2364   

   fractal_dimension_worst  
0                  0.11890  
1                  0.08902  
2                  0.08758  
3                  0.17300  
4                  0.07678  

[5 rows x 31 columns]

In [112]:
# Normalize the numeric variable from column2 to column31 in the dataframe

In [113]:
minmax=preprocessing.MinMaxScaler(feature_range=(0,1))
minmax.fit(x).transform(x)

array([[0.52103744, 0.0226581 , 0.54598853, ..., 0.91202749, 0.59846245,
        0.41886396],
       [0.64314449, 0.27257355, 0.61578329, ..., 0.63917526, 0.23358959,
        0.22287813],
       [0.60149557, 0.3902604 , 0.59574321, ..., 0.83505155, 0.40370589,
        0.21343303],
       ...,
       [0.45525108, 0.62123774, 0.44578813, ..., 0.48728522, 0.12872068,
        0.1519087 ],
       [0.64456434, 0.66351031, 0.66553797, ..., 0.91065292, 0.49714173,
        0.45231536],
       [0.03686876, 0.50152181, 0.02853984, ..., 0.        , 0.25744136,
        0.10068215]])

In [96]:
x["area_mean"].describe()

count     569.000000
mean      654.889104
std       351.914129
min       143.500000
25%       420.300000
50%       551.100000
75%       782.700000
max      2501.000000
Name: area_mean, dtype: float64

In [97]:
from sklearn import cross_validation,neighbors
from sklearn.cross_validation import train_test_split

In [98]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [99]:
x_train

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
384       13.280         13.72           85.79      541.8          0.08363   
428       11.130         16.62           70.47      381.1          0.08151   
327       12.030         17.93           76.09      446.0          0.07683   
408       17.990         20.66          117.80      991.7          0.10360   
548        9.683         19.34           61.05      285.7          0.08491   
439       14.020         15.66           89.59      606.5          0.07966   
63         9.173         13.86           59.20      260.9          0.07721   
484       15.730         11.28          102.80      747.2          0.10430   
213       17.420         25.56          114.50      948.0          0.10060   
328       16.270         20.71          106.90      813.7          0.11690   
465       13.240         20.13           86.87      542.9          0.08284   
252       19.730         19.82          130.70     1206.0          0.10620   
254       19.450         19.33          126.50     1169.0          0.10350   
198       19.180         22.49          127.50     1148.0          0.08523   
220       13.650         13.16           87.88      568.9          0.09646   
44        13.170         21.81           85.42      531.5          0.09714   
59         8.618         11.79           54.34      224.5          0.09752   
388       11.270         15.50           73.38      392.0          0.08365   
56        19.210         18.57          125.50     1152.0          0.10530   
161       19.190         15.94          126.30     1157.0          0.08694   
298       14.260         18.17           91.22      633.1          0.06576   
172       15.460         11.89          102.50      736.9          0.12570   
186       18.310         18.58          118.60     1041.0          0.08588   
36        14.250         21.72           93.63      633.0          0.09823   
323       20.340         21.51          135.90     1264.0          0.11700   
272       21.750         20.99          147.30     1491.0          0.09401   
506       12.220         20.04           79.47      453.1          0.10960   
420       11.570         19.04           74.20      409.7          0.08546   
258       15.660         23.20          110.20      773.5          0.11090   
493       12.460         12.83           78.83      477.3          0.07372   
..           ...           ...             ...        ...              ...   
226       10.440         15.46           66.62      329.6          0.10530   
202       23.290         26.67          158.90     1685.0          0.11410   
397       12.800         17.46           83.05      508.3          0.08044   
179       12.810         13.06           81.29      508.8          0.08739   
41        10.950         21.35           71.90      371.1          0.12270   
396       13.510         18.89           88.10      558.1          0.10590   
445       11.990         24.89           77.61      441.3          0.10300   
241       12.420         15.04           78.61      476.5          0.07926   
235       14.030         21.25           89.79      603.4          0.09070   
53        18.220         18.70          120.30     1033.0          0.11480   
301       12.460         19.89           80.43      471.3          0.08451   
151        8.219         20.70           53.27      203.9          0.09405   
248       10.650         25.22           68.01      347.0          0.09657   
411       11.040         16.83           70.92      373.2          0.10770   
50        11.760         21.60           74.72      427.9          0.08637   
66         9.465         21.01           60.11      269.4          0.10440   
551       11.130         22.44           71.49      378.4          0.09566   
549       10.820         24.21           68.89      361.6          0.08192   
483       13.700         17.64           87.76      571.1          0.09950   
475       12.830         15

In [100]:
y_train=y_train.astype('int')
y_test=y_test.astype('int')

In [101]:
# Fitting Classifier to the Training set
clf=neighbors.KNeighborsClassifier()
clf.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [102]:
# pedict on the test
y_pred=clf.predict(x_test)


In [103]:
y_test.values

array([0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0])

In [104]:
y_pred

array([0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0])

In [105]:
clf.score(x_train,y_train)

0.9406593406593406

In [106]:
clf.score(x_test,y_test)

0.9473684210526315

In [107]:
# Accuracy score on test and train
from sklearn.metrics import accuracy_score,recall_score,roc_auc_score,confusion_matrix

In [108]:
accuracy_score(y_test,y_pred)

0.9473684210526315

In [109]:
recall_score(y_test,y_pred)

0.9302325581395349

In [110]:
roc_auc_score(y_test,y_pred)

0.9439895185063871

In [111]:
confusion_matrix(y_test,y_pred)

array([[68,  3],
       [ 3, 40]], dtype=int64)