In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [2]:
data=pd.read_csv("diabetes.csv")
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age Diabetes  
0                     0.627   50      pos  
1                     0.351   31      neg  
2                     0.672   32      pos  
3                     0.167   21      neg  
4                     2.288   33      pos

In [3]:
data.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age  
count  768.000000                768.000000  768.000000  
mean    31.992578                  0.471876   33.240885  
std      7.884160                  0.331329   11.760232  
min      0.000000                  0.078000   21.000000  
25%     27.300000                  0.243750   24.000000  
50%     32.000000                  0.372500   29.000000  
75%     36.600000                  0.626250   41.000000  
max     67.100000                  2.420000   81.000000

In [4]:
data["Diabetes"].replace(['pos','neg'],[1,0],inplace=True)

In [5]:
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Diabetes  
0                     0.627   50         1  
1                     0.351   31         0  
2                     0.672   32         1  
3                     0.167   21         0  
4                     2.288   33         1

In [6]:
features=data.iloc[:,1:8]
features.head()

Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0      148             72             35        0  33.6   
1       85             66             29        0  26.6   
2      183             64              0        0  23.3   
3       89             66             23       94  28.1   
4      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [7]:
labels=data.iloc[:,-1]
labels.head()

0    1
1    0
2    1
3    0
4    1
Name: Diabetes, dtype: int64

In [8]:
minmax=preprocessing.MinMaxScaler(feature_range=(0,1))
minmax.fit(features).transform(features)

array([[0.74371859, 0.59016393, 0.35353535, ..., 0.50074516, 0.23441503,
        0.48333333],
       [0.42713568, 0.54098361, 0.29292929, ..., 0.39642325, 0.11656704,
        0.16666667],
       [0.91959799, 0.52459016, 0.        , ..., 0.34724292, 0.25362938,
        0.18333333],
       ...,
       [0.6080402 , 0.59016393, 0.23232323, ..., 0.390462  , 0.07130658,
        0.15      ],
       [0.63316583, 0.49180328, 0.        , ..., 0.4485842 , 0.11571307,
        0.43333333],
       [0.46733668, 0.57377049, 0.31313131, ..., 0.45305514, 0.10119556,
        0.03333333]])

In [9]:
from sklearn import cross_validation,neighbors
from sklearn.cross_validation import train_test_split
x_train,x_test,y_train,y_test=train_test_split(features,labels,test_size=0.2)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [10]:
x_train.shape

(614, 7)

In [11]:
x_test.shape

(154, 7)

689    1
462    0
326    1
67     0
249    0
Name: Diabetes, dtype: int32

In [13]:
clf=neighbors.KNeighborsClassifier()
clf.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [14]:
y=clf.predict(x_test)
y

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0])

In [15]:
y_test.head()

553    0
600    0
327    0
240    0
303    1
Name: Diabetes, dtype: int64

In [16]:
y_test=y_test.astype("int")

In [17]:
from sklearn.metrics import accuracy_score,recall_score,roc_auc_score,confusion_matrix

In [18]:
accuracy_score(y_test,y)

0.7012987012987013

In [19]:
recall_score(y_test,y)

0.5166666666666667

In [20]:
roc_auc_score(y_test,y)

0.6679078014184398

In [21]:
confusion_matrix(y_test,y)

array([[77, 17],
       [29, 31]], dtype=int64)

In [22]:
features=data.iloc[:,1:3]
features.head()

Glucose  BloodPressure
0      148             72
1       85             66
2      183             64
3       89             66
4      137             40

In [23]:
minmax=preprocessing.MinMaxScaler(feature_range=(0,1))b
minmax.fit(features).transform(features)

array([[0.74371859, 0.59016393],
       [0.42713568, 0.54098361],
       [0.91959799, 0.52459016],
       ...,
       [0.6080402 , 0.59016393],
       [0.63316583, 0.49180328],
       [0.46733668, 0.57377049]])

In [24]:
x_train,x_test,y_train,y_test=train_test_split(features,labels,test_size=0.2)

In [25]:
y_train=y_train.astype('int')
y_train.head()

557    0
54     0
549    0
464    0
624    0
Name: Diabetes, dtype: int32

In [26]:
clf=neighbors.KNeighborsClassifier()
clf.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [27]:
y=clf.predict(x_test)
y

array([0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1])

In [28]:
y_test=y_test.astype("int")

In [29]:
accuracy_score(y_test,y)

0.7207792207792207

In [30]:
recall_score(y_test,y)

0.5245901639344263

In [31]:
roc_auc_score(y_test,y)

0.6870262647629121

In [32]:
confusion_matrix(y_test,y)

array([[79, 14],
       [29, 32]], dtype=int64)

In [33]:
features=data.iloc[:,1:5]
features.head()

Glucose  BloodPressure  SkinThickness  Insulin
0      148             72             35        0
1       85             66             29        0
2      183             64              0        0
3       89             66             23       94
4      137             40             35      168

In [34]:
minmax=preprocessing.MinMaxScaler(feature_range=(0,1))
minmax.fit(features).transform(features)

array([[0.74371859, 0.59016393, 0.35353535, 0.        ],
       [0.42713568, 0.54098361, 0.29292929, 0.        ],
       [0.91959799, 0.52459016, 0.        , 0.        ],
       ...,
       [0.6080402 , 0.59016393, 0.23232323, 0.13238771],
       [0.63316583, 0.49180328, 0.        , 0.        ],
       [0.46733668, 0.57377049, 0.31313131, 0.        ]])

In [35]:
x_train,x_test,y_train,y_test=train_test_split(features,labels,test_size=0.2)

In [36]:
y_train=y_train.astype('int')
y_train.head()

641    0
368    0
477    0
187    1
599    0
Name: Diabetes, dtype: int32

In [37]:
clf=neighbors.KNeighborsClassifier()
clf.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [38]:
y=clf.predict(x_test)
y

array([1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0])

In [39]:
y_test=y_test.astype("int")

In [40]:
accuracy_score(y_test,y)

0.7402597402597403

In [41]:
recall_score(y_test,y)

0.5777777777777777

In [42]:
roc_auc_score(y_test,y)

0.6925586136595311

In [43]:
confusion_matrix(y_test,y)

array([[88, 21],
       [19, 26]], dtype=int64)